### ISSUE TITLE
Documentation pls!

### ISSUE THREAD

**Issue by nfgrep** [0xA2A3/montecarlo#1]
Love the repo, documentation lacking though.  
**Would like to see:**
- [x] Comments throughout the library and in the main execution file
- [x] A [wiki](https://guides.github.com/features/wikis/#creating-your-wiki), describing each module in the library
- [x] Maybe some tutorials/learning resources that guide me through the modules of the library in the wiki

**Comment by militarize** [comment]
Working on these currently.

**Comment by militarize** [comment]
Hello,

I am currently overhauling the project and code. The wiki will be intended for code documentation. And, hopefully, the [project page](https://0xa2a3.github.io/montecarlo) will serve for "tutorials". Since the intention is to build this incrementally, major changes from this point should be accompanied with documentation.

I am closing this issue for now.
